# Copyright (c) 2023 ...

From docker.io/library/golang:1.20.6-alpine as builder

WORKDIR /app

# Download necessary Go modules
COPY go.mod ./
COPY go.sum ./
RUN go mod download

#build an app
COPY cmd/ cmd/
RUN go build -v -o /testclient /app/cmd/...

CMD [ "/testclient", "localhost" ]
