# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x14opi_api.inventory.v1\"\xbf\x01\n\nDeviceInfo\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x10\n\x08mfg_name\x18\x04 \x01(\t\x12\x10\n\x08mfg_date\x18\x05 \x01(\t\x12\x12\n\nhw_version\x18\x06 \x01(\t\x12\x12\n\nfw_version\x18\x07 \x01(\t\x12\x12\n\nsw_version\x18\x08 \x01(\t\x12\x11\n\tserial_no\x18\t \x01(\t\x12\x0f\n\x07part_no\x18\n \x01(\t\"\x07\n\x05\x45mpty\"z\n\x14InventoryGetResponse\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.opi_api.inventory.v1.APIStatus\x12\x31\n\x07\x44\x65vInfo\x18\x02 \x01(\x0b\x32 .opi_api.inventory.v1.DeviceInfo*4\n\tAPIStatus\x12\x11\n\rAPI_STATUS_OK\x10\x00\x12\x14\n\x10\x41PI_STATUS_ERROR\x10\x01\x32i\n\x0cInventorySvc\x12Y\n\x0cInventoryGet\x12\x1b.opi_api.inventory.v1.Empty\x1a*.opi_api.inventory.v1.InventoryGetResponse\"\x00\x42\x30Z.github.com/opiproject/opi-api/common/v1/gen/gob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z.github.com/opiproject/opi-api/common/v1/gen/go'
  _APISTATUS._serialized_start=368
  _APISTATUS._serialized_end=420
  _DEVICEINFO._serialized_start=42
  _DEVICEINFO._serialized_end=233
  _EMPTY._serialized_start=235
  _EMPTY._serialized_end=242
  _INVENTORYGETRESPONSE._serialized_start=244
  _INVENTORYGETRESPONSE._serialized_end=366
  _INVENTORYSVC._serialized_start=422
  _INVENTORYSVC._serialized_end=527
# @@protoc_insertion_point(module_scope)
