# Copyright (c) 2023 ...

FROM docker.io/library/golang:1.20.6-alpine as builder

WORKDIR /app

# Download necessary Go modules
COPY go.mod ./
COPY go.sum ./
RUN go mod download

#build an app
COPY cmd/ cmd/
COPY pkg/ pkg/
RUN go build -v -o /nwgate /app/cmd/...

EXPOSE 50153

CMD [ "/nwgate" ]
